#pragma once
# ifndef CONSTANTS_H
# define CONSTANTS_H
# define BLACKAREARANGE 60
# define BACKGROUNDSUBSTRACTIONLENGTH 30
# define EROSION 1
# define AMOUNTOFBALLS 20
# define DILATATION 2
# define HEIGHT = 240
# define WIDTH = 320
# define LOWER_THRESHOLD 1.15
# define UPPER_THRESHOLD 1.15
# define UPPER_DELTA 20
# define LOWER_DELTA 20
# define BRIGHTNESS 130
# define PI 3.14159262
# define MEANROWFEATURELENGTH 8
# define COMPWIDTH 160
# define COMPHEIGHT 90
# define MINPIXELCOUNT 50
# define MAXPIXELCOUNT 2000
# define MINPERSONWIDTH COMPWIDTH/30
# define MINPERSONHEIGHT COMPHEIGHT/5
# define COLORSIMILARITY 32
# define PERSONNOTFOUNDCOUNTER 5
# define EUCLIDIANDISTANCEOFFSET 7


#endif  // CONSTANTS_H