#pragma once
#ifndef CONSTANTS_H
#define CONSTANTS_H
#define BLACKAREARANGE 60
# define BACKGROUNDSUBSTRACTIONLENGTH 30
# define EROSION 1
# define AMOUNTOFBALLS 10
# define DILATATION 2
# define HEIGHT = 240;
# define WIDTH = 320
# define LOWER_THRESHOLD 1.15
# define UPPER_THRESHOLD 1.15
# define UPPER_DELTA 15
# define LOWER_DELTA 15
# define BRIGHTNESS 130
# define PI 3.14159262
# define BODYCOLORLENGTH 8
# define COMPWIDTH 160
# define COMPHEIGHT 90
# define MINPIXELCOUNT 250
# define MAXPIXELCOUNT 2000
# define MINPERSONWIDTH 10
# define MINPERSONHEIGHT 20



#endif  // CONSTANTS_H